# Generated by Django 4.2.4 on 2025-05-23 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('fin_prdt_cd', models.CharField(help_text='금융상품 코드', max_length=100, primary_key=True, serialize=False)),
                ('kor_co_nm', models.CharField(help_text='금융회사명', max_length=100)),
                ('fin_prdt_nm', models.CharField(help_text='금융상품명', max_length=255)),
                ('join_way', models.TextField(blank=True, help_text='가입 방법', null=True)),
                ('mtrt_int', models.TextField(blank=True, help_text='만기 후 이자율 설명', null=True)),
                ('spcl_cnd', models.TextField(blank=True, help_text='우대조건', null=True)),
                ('join_deny', models.CharField(blank=True, help_text='가입제한 (1:제한없음, 2:서민전용, 3:일부제한)', max_length=50, null=True)),
                ('join_member', models.TextField(blank=True, help_text='가입대상', null=True)),
                ('etc_note', models.TextField(blank=True, help_text='기타 유의사항', null=True)),
                ('max_limit', models.BigIntegerField(blank=True, help_text='최고한도', null=True)),
                ('dcls_strt_day', models.CharField(blank=True, help_text='공시 시작일', max_length=8, null=True)),
                ('dcls_end_day', models.CharField(blank=True, help_text='공시 종료일', max_length=8, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, help_text='금융회사 제출일', max_length=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('fin_prdt_cd', models.CharField(help_text='금융상품 코드', max_length=100, primary_key=True, serialize=False)),
                ('kor_co_nm', models.CharField(help_text='금융회사명', max_length=100)),
                ('fin_prdt_nm', models.CharField(help_text='금융상품명', max_length=255)),
                ('join_way', models.TextField(blank=True, help_text='가입 방법', null=True)),
                ('mtrt_int', models.TextField(blank=True, help_text='만기 후 이자율 설명', null=True)),
                ('spcl_cnd', models.TextField(blank=True, help_text='우대조건', null=True)),
                ('join_deny', models.CharField(blank=True, help_text='가입제한 (1:제한없음, 2:서민전용, 3:일부제한)', max_length=50, null=True)),
                ('join_member', models.TextField(blank=True, help_text='가입대상', null=True)),
                ('etc_note', models.TextField(blank=True, help_text='기타 유의사항', null=True)),
                ('max_limit', models.BigIntegerField(blank=True, help_text='최고한도', null=True)),
                ('dcls_strt_day', models.CharField(blank=True, help_text='공시 시작일', max_length=8, null=True)),
                ('dcls_end_day', models.CharField(blank=True, help_text='공시 종료일', max_length=8, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, help_text='금융회사 제출일', max_length=12, null=True)),
                ('rsrv_type', models.CharField(blank=True, help_text='적립 유형 (F:자유적립식, S:정액적립식)', max_length=1, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, help_text='적립 유형명', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='products.savingproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '적금 상품 구독',
                'verbose_name_plural': '적금 상품 구독 목록',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(help_text='이자율 종류 (S:단리, M:복리)', max_length=1)),
                ('intr_rate_type_nm', models.CharField(help_text='이자율 종류명 (단리/복리)', max_length=10)),
                ('save_trm', models.CharField(help_text='저축 기간 (개월)', max_length=3)),
                ('intr_rate', models.DecimalField(blank=True, decimal_places=2, help_text='저축 금리 (소수점 2자리)', max_digits=5, null=True)),
                ('intr_rate2', models.DecimalField(blank=True, decimal_places=2, help_text='최고 우대금리 (소수점 2자리)', max_digits=5, null=True)),
                ('acc_type_nm', models.CharField(blank=True, help_text='적금 종류명(청년/일반 등)', max_length=20, null=True)),
                ('product', models.ForeignKey(help_text='연관 적금상품 코드', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.savingproduct')),
            ],
            options={
                'abstract': False,
                'unique_together': {('product', 'intr_rate_type', 'save_trm')},
            },
        ),
        migrations.CreateModel(
            name='DepositSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='products.depositproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '예금 상품 구독',
                'verbose_name_plural': '예금 상품 구독 목록',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(help_text='이자율 종류 (S:단리, M:복리)', max_length=1)),
                ('intr_rate_type_nm', models.CharField(help_text='이자율 종류명 (단리/복리)', max_length=10)),
                ('save_trm', models.CharField(help_text='저축 기간 (개월)', max_length=3)),
                ('intr_rate', models.DecimalField(blank=True, decimal_places=2, help_text='저축 금리 (소수점 2자리)', max_digits=5, null=True)),
                ('intr_rate2', models.DecimalField(blank=True, decimal_places=2, help_text='최고 우대금리 (소수점 2자리)', max_digits=5, null=True)),
                ('product', models.ForeignKey(help_text='연관 예금상품 코드', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.depositproduct')),
            ],
            options={
                'abstract': False,
                'unique_together': {('product', 'intr_rate_type', 'save_trm')},
            },
        ),
    ]
