# Generated by Django 4.2.4 on 2025-05-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositProduct",
            fields=[
                (
                    "fin_prdt_cd",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("kor_co_nm", models.CharField(max_length=100)),
                ("fin_prdt_nm", models.CharField(max_length=200)),
                ("etc_note", models.TextField()),
                ("join_deny", models.IntegerField()),
                ("join_member", models.CharField(max_length=100)),
                ("join_way", models.CharField(max_length=100)),
                ("spcl_cnd", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="DepositOption",
            fields=[
                ("option_id", models.AutoField(primary_key=True, serialize=False)),
                ("intr_rate_type_nm", models.CharField(max_length=50)),
                ("save_trm", models.IntegerField()),
                ("intr_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("intr_rate2", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "fin_prdt_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.depositproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "unique_together": {("asset_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fin_prdt_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.depositproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "fin_prdt_cd")},
            },
        ),
    ]
