# Generated by Django 4.2.4 on 2025-05-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depositsubscription",
            options={
                "ordering": ["-subscribed_at"],
                "verbose_name": "예금 상품 구독",
                "verbose_name_plural": "예금 상품 구독 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="savingsubscription",
            options={
                "ordering": ["-subscribed_at"],
                "verbose_name": "적금 상품 구독",
                "verbose_name_plural": "적금 상품 구독 목록",
            },
        ),
        migrations.AlterUniqueTogether(
            name="depositsubscription",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="savingsubscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="depositsubscription",
            name="amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="depositsubscription",
            name="option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="products.depositoption",
            ),
        ),
        migrations.AddField(
            model_name="savingsubscription",
            name="amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="savingsubscription",
            name="option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="products.savingoption",
            ),
        ),
        migrations.AlterField(
            model_name="depositsubscription",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="products.depositproduct",
            ),
        ),
        migrations.AlterField(
            model_name="savingsubscription",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="products.savingproduct",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="depositsubscription",
            unique_together={("user", "product", "option")},
        ),
        migrations.AlterUniqueTogether(
            name="savingsubscription",
            unique_together={("user", "product", "option")},
        ),
    ]
