# Generated by Django 4.2.4 on 2025-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': '자산 가격',
                'verbose_name_plural': '자산 가격들',
                'ordering': ['date'],
                'unique_together': {('asset_name', 'date')},
            },
        ),
    ]
