# Generated by Django 4.2.4 on 2025-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=10, unique=True, verbose_name='지수명')),
                ('current_value', models.FloatField(verbose_name='현재 지수')),
                ('change', models.FloatField(verbose_name='전일 대비 변동폭')),
                ('change_rate', models.FloatField(verbose_name='전일 대비 등락률 (%)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트 시간')),
            ],
            options={
                'verbose_name': '시장 지수',
                'verbose_name_plural': '시장 지수 목록',
                'ordering': ['name'],
            },
        ),
    ]
