# Generated by Django 4.2.4 on 2025-05-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_indices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketindex',
            name='change_rate',
        ),
        migrations.RemoveField(
            model_name='marketindex',
            name='current_value',
        ),
        migrations.AddField(
            model_name='marketindex',
            name='rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketindex',
            name='value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketindex',
            name='change',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marketindex',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketindex',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
