# Generated by Django 4.2.4 on 2025-05-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_parent_comment_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='parent',
        ),
    ]
