# Generated by Django 4.2.4 on 2025-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_rename_parent_comment_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
