# Generated by Django 4.2.4 on 2025-05-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="social_profile_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
