# Generated by Django 4.2.4 on 2025-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favoritevideo_favoritechannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritevideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
