# Generated by Django 4.2.4 on 2025-05-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscribed_products",
            field=models.ManyToManyField(blank=True, to="products.depositproduct"),
        ),
    ]
