# Generated by Django 4.2.4 on 2025-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_age_alter_profile_amount_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount_available',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
