# Generated by Django 4.2.4 on 2025-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_favoritevideo_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
